version: '3.8'

services:
  # Service de l'application Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - db
    networks:
      - app-network

  # Service de la base de données PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-crm_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-azerty123AZERTY}
      - POSTGRES_DB=${POSTGRES_DB:-lm_commande_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Service de gestion de la base de données (optionnel)
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge 